export interface ActivityItem {
  id: string;
  name: string;
  cityId: string;
  city: string;
  country: string;
  region: string;
  category: string;
  categoryGroup: 'adventure' | 'sightseeing' | 'food' | 'culture' | 'relaxation' | 'cruise' | 'transfer';
  time: string;
  duration: string;
  durationMinutes: number;
  cost: number;
  costTier: 'budget' | 'moderate' | 'luxury';
  costLabel: string;
  popularity: number;
  reviewsCount: string;
  imageUrl: string;
  description: string;
  highlights: string[];
}

export interface DayPlan {
  dayNumber: number;
  date: string;
  dayOfMonth: number;
  city: string;
  country: string;
  title: string;
  dailyCap: number;
  activities: ActivityItem[];
}

export interface SectionItem {
  id: string;
  sectionNumber: number;
  title: string;
  category: 'travel' | 'hotel' | 'activity' | 'city';
  city: string;
  country: string;
  imageUrl: string;
  description: string;
  startDate: string;
  endDate: string;
  budget: number;
  activities: ActivityItem[];
}

export interface TripSpanItem {
  id: string;
  title: string;
  city: string;
  country: string;
  color: string;
  badgeBg: string;
  badgeText: string;
  startDay: number;
  endDay: number;
}

// =========================================================================
// SYNCHRONIZED MASTER DEMO TRIP: "Europe Grand Discovery 2026"
// Dates: Sep 10, 2026 – Sep 28, 2026 (Total Budget Cap: ₹1,60,000 | Est: ₹1,52,000)
// =========================================================================

export const MASTER_TRIP = {
  id: '66c6de59b583f7b2cb1e8921',
  name: 'Europe Grand Discovery 2026',
  startDate: 'Sep 10, 2026',
  endDate: 'Sep 28, 2026',
  budgetCap: 160000,
  totalEstimatedCost: 152000,
  daysCount: 14,
  stopsCount: 3,
  cities: 'Paris • Swiss Alps • Rome • Barcelona',
  coverImageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=85',
};

// 1. ALL ACTIVITIES (Master List)
export const MASTER_ACTIVITIES: ActivityItem[] = [
  // PARIS (Sep 10 - 13)
  {
    id: 'p-1',
    name: 'Airport VIP Chauffeur Transfer to Hotel',
    cityId: 'c-paris',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    category: 'Airport Transfer',
    categoryGroup: 'transfer',
    time: '10:00 AM',
    duration: '1.5 Hours',
    durationMinutes: 90,
    cost: 4500,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.8,
    reviewsCount: '1.4k',
    imageUrl: 'https://images.unsplash.com/photo-1549144511-f099e773c147?w=800&q=80',
    description: 'Private executive Mercedes chauffeur transfer directly to your central boutique hotel near the Seine.',
    highlights: ['Mercedes Executive Sedan', 'Luggage Porter Assistance', 'Instant Hotel Check-in'],
  },
  {
    id: 'p-2',
    name: 'Louvre Museum Masterpieces Guided Tour',
    cityId: 'c-paris',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    category: 'Museum & Art',
    categoryGroup: 'culture',
    time: '02:30 PM',
    duration: '2.5 Hours',
    durationMinutes: 150,
    cost: 5200,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.9,
    reviewsCount: '5.2k',
    imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80',
    description: 'Skip-the-line entrance with expert art historian guide to view the Mona Lisa, Venus de Milo, and French Crown Jewels.',
    highlights: ['Skip-the-line pass', 'Mona Lisa priority viewing', 'Curated historic commentary'],
  },
  {
    id: 'p-3',
    name: 'Seine River Romantic Sunset Dinner Cruise',
    cityId: 'c-paris',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    category: 'Cruise & Dining',
    categoryGroup: 'cruise',
    time: '07:00 PM',
    duration: '2.5 Hours',
    durationMinutes: 150,
    cost: 6800,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.8,
    reviewsCount: '4.1k',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    description: '3-course French gourmet meal onboard a panoramic glass boat facing the sparkling illuminated Eiffel Tower.',
    highlights: ['3-course gourmet dinner', 'Champagne welcome toast', 'Live acoustic French music'],
  },
  {
    id: 'p-4',
    name: 'Montmartre Artists Quarter & Sacré-Cœur Walking Tour',
    cityId: 'c-paris',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    category: 'Cultural Walk',
    categoryGroup: 'culture',
    time: '09:30 AM',
    duration: '2.0 Hours',
    durationMinutes: 120,
    cost: 3200,
    costTier: 'budget',
    costLabel: '₹ Budget',
    popularity: 4.8,
    reviewsCount: '3.1k',
    imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800&q=80',
    description: 'Explore cobblestone alleys, artist squares, and breathtaking panoramic hill views across Paris.',
    highlights: ['Sacré-Cœur Basilica entry', 'Historic Moulin Rouge exterior', 'Local bakery macaron tasting'],
  },
  {
    id: 'p-5',
    name: 'Palais Garnier Opera House Private Access',
    cityId: 'c-paris',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    category: 'Architecture',
    categoryGroup: 'sightseeing',
    time: '02:00 PM',
    duration: '2.0 Hours',
    durationMinutes: 120,
    cost: 4100,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.8,
    reviewsCount: '2.4k',
    imageUrl: 'https://images.unsplash.com/photo-1520939817895-060bdef4ad1b?w=800&q=80',
    description: 'Gilded grand foyers, phantom of the opera history, and royal theater boxes.',
    highlights: ['Grand staircase photography', 'Auditorium access', 'Chagall painted ceiling'],
  },
  {
    id: 'p-6',
    name: 'Eiffel Tower Top Floor Access & Champagne Bar',
    cityId: 'c-paris',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    category: 'Landmark',
    categoryGroup: 'sightseeing',
    time: '06:30 PM',
    duration: '2.5 Hours',
    durationMinutes: 150,
    cost: 5800,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.9,
    reviewsCount: '7.8k',
    imageUrl: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=800&q=80',
    description: 'Direct summit elevator pass with panoramic 360-degree night views over illuminated Paris.',
    highlights: ['Summit elevator pass', 'Glass floor observatory', 'Evening sparkling lights show'],
  },

  // SWISS ALPS (Sep 14 - 18)
  {
    id: 's-1',
    name: 'Scenic Glacier Express 1st Class Train Transfer',
    cityId: 'c-swiss',
    city: 'Interlaken',
    country: 'Switzerland',
    region: 'Europe',
    category: 'Scenic Train',
    categoryGroup: 'transfer',
    time: '09:00 AM',
    duration: '3.5 Hours',
    durationMinutes: 210,
    cost: 7500,
    costTier: 'luxury',
    costLabel: '₹₹₹ Luxury',
    popularity: 4.9,
    reviewsCount: '3.6k',
    imageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80',
    description: 'Panoramic glass dome train winding through alpine meadows into Interlaken beneath snow-capped peaks.',
    highlights: ['Glacier Express 1st class', 'Luggage porter service', 'Alpine mountain pass views'],
  },
  {
    id: 's-2',
    name: 'Turquoise Lake Brienz Steamer & Giessbach Falls',
    cityId: 'c-swiss',
    city: 'Interlaken',
    country: 'Switzerland',
    region: 'Europe',
    category: 'Lake & Nature',
    categoryGroup: 'cruise',
    time: '02:00 PM',
    duration: '2.5 Hours',
    durationMinutes: 150,
    cost: 4200,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.8,
    reviewsCount: '2.1k',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    description: 'Cruise crystal turquoise waters surrounded by towering 4000m peaks to Giessbach waterfalls.',
    highlights: ['Steamer boat cruise', 'Historic funicular railway', 'Waterfall trail walk'],
  },
  {
    id: 's-3',
    name: 'Traditional Swiss Fondue & Raclette Chalet Dinner',
    cityId: 'c-swiss',
    city: 'Interlaken',
    country: 'Switzerland',
    region: 'Europe',
    category: 'Gastronomy',
    categoryGroup: 'food',
    time: '07:30 PM',
    duration: '2.0 Hours',
    durationMinutes: 120,
    cost: 4800,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.8,
    reviewsCount: '1.9k',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    description: 'Authentic wood-chalet cheese fondue experience paired with Valais white wine.',
    highlights: ['Artisanal Gruyere fondue', 'Fresh baked rösti', 'Swiss chocolate dessert'],
  },
  {
    id: 's-4',
    name: 'Jungfraujoch Top of Europe Cogwheel Express Pass',
    cityId: 'c-swiss',
    city: 'Interlaken',
    country: 'Switzerland',
    region: 'Europe',
    category: 'Summit Adventure',
    categoryGroup: 'adventure',
    time: '08:30 AM',
    duration: '5.0 Hours',
    durationMinutes: 300,
    cost: 14500,
    costTier: 'luxury',
    costLabel: '₹₹₹ Luxury',
    popularity: 4.9,
    reviewsCount: '3.4k',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    description: 'Climb inside the mountain to the highest railway station in Europe at 3,454 meters.',
    highlights: ['Eiger Glacier 360 Express', 'Ice Palace tunnels pass', 'Sphinx Observatory ticket'],
  },
  {
    id: 's-5',
    name: 'Grindelwald First Cliff Walk by Tissot',
    cityId: 'c-swiss',
    city: 'Interlaken',
    country: 'Switzerland',
    region: 'Europe',
    category: 'Thrill & View',
    categoryGroup: 'adventure',
    time: '03:00 PM',
    duration: '2.0 Hours',
    durationMinutes: 120,
    cost: 3800,
    costTier: 'budget',
    costLabel: '₹ Budget',
    popularity: 4.8,
    reviewsCount: '2.7k',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    description: 'Suspended metal walkway along steel bridge structure overlooking Grindelwald valley.',
    highlights: ['Suspension bridge walk', 'First flyer zipline option', 'Panoramic terrace photos'],
  },
  {
    id: 's-6',
    name: 'Tandem Paragliding Over Interlaken & Lake Brienz',
    cityId: 'c-swiss',
    city: 'Interlaken',
    country: 'Switzerland',
    region: 'Europe',
    category: 'Paragliding & Adventure',
    categoryGroup: 'adventure',
    time: '10:00 AM',
    duration: '1.5 Hours',
    durationMinutes: 90,
    cost: 8500,
    costTier: 'luxury',
    costLabel: '₹₹₹ Luxury',
    popularity: 4.9,
    reviewsCount: '2.8k',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    description: 'Experience the ultimate rush soaring with certified Swiss tandem pilots above Jungfrau snow peaks.',
    highlights: ['GoPro HD video package included', 'All safety gear & pilot instruction', 'Hotel pickup & drop-off'],
  },

  // ROME (Sep 19 - 23)
  {
    id: 'r-1',
    name: 'Colosseum Arena Floor & Underground Gladiator Pass',
    cityId: 'c-rome',
    city: 'Rome',
    country: 'Italy',
    region: 'Europe',
    category: 'Historical Landmark',
    categoryGroup: 'sightseeing',
    time: '09:30 AM',
    duration: '3.0 Hours',
    durationMinutes: 180,
    cost: 6500,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.9,
    reviewsCount: '5.6k',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    description: 'Exclusive access onto the arena floor where gladiators fought, plus Roman Forum.',
    highlights: ['Gladiator arena floor VIP pass', 'Palatine Hill imperial palaces', 'Roman Forum guided tour'],
  },
  {
    id: 'r-2',
    name: 'Pantheon Temple & Trevi Fountain Historic Walk',
    cityId: 'c-rome',
    city: 'Rome',
    country: 'Italy',
    region: 'Europe',
    category: 'Walking Tour',
    categoryGroup: 'culture',
    time: '02:30 PM',
    duration: '2.0 Hours',
    durationMinutes: 120,
    cost: 2800,
    costTier: 'budget',
    costLabel: '₹ Budget',
    popularity: 4.8,
    reviewsCount: '4.2k',
    imageUrl: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&q=80',
    description: 'Marvel at ancient domed architecture, throw a coin in Trevi, and savor espresso.',
    highlights: ['Pantheon interior entry', 'Trevi Fountain photo spot', 'Sant Eustachio espresso tasting'],
  },
  {
    id: 'r-3',
    name: 'Trastevere Foodie Walk: Handmade Pasta & Wine',
    cityId: 'c-rome',
    city: 'Rome',
    country: 'Italy',
    region: 'Europe',
    category: 'Food & Wine',
    categoryGroup: 'food',
    time: '07:00 PM',
    duration: '3.5 Hours',
    durationMinutes: 210,
    cost: 5400,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.9,
    reviewsCount: '3.9k',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    description: 'Authentic 4-course progressive dinner through Rome’s most vibrant cobblestone district.',
    highlights: ['Carbonara & Cacio e Pepe', 'Chianti & Barolo pairings', 'Award-winning artisanal gelato'],
  },
  {
    id: 'r-4',
    name: 'Vatican Museums & Sistine Chapel Early Access',
    cityId: 'c-rome',
    city: 'Rome',
    country: 'Italy',
    region: 'Europe',
    category: 'Museum & Faith',
    categoryGroup: 'culture',
    time: '08:00 AM',
    duration: '3.5 Hours',
    durationMinutes: 210,
    cost: 6800,
    costTier: 'moderate',
    costLabel: '₹₹ Moderate',
    popularity: 4.9,
    reviewsCount: '6.4k',
    imageUrl: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=800&q=80',
    description: 'Enter before general crowds to admire Michelangelo’s ceiling in quiet splendor.',
    highlights: ['Early bird VIP entrance', 'Sistine Chapel private viewing', 'St. Peter’s Basilica access'],
  },
  {
    id: 'r-5',
    name: 'Castel Sant’Angelo Fortress & Angel Bridge',
    cityId: 'c-rome',
    city: 'Rome',
    country: 'Italy',
    region: 'Europe',
    category: 'Castle & Views',
    categoryGroup: 'sightseeing',
    time: '02:30 PM',
    duration: '2.0 Hours',
    durationMinutes: 120,
    cost: 3400,
    costTier: 'budget',
    costLabel: '₹ Budget',
    popularity: 4.8,
    reviewsCount: '2.9k',
    imageUrl: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800&q=80',
    description: 'Papal fortress with secret passage corridors and rooftop terrace across Rome.',
    highlights: ['Castle rooftop terrace', 'Passetto di Borgo corridor', 'Ponte Sant’Angelo bridge views'],
  },
  {
    id: 'r-6',
    name: 'Piazza Navona Evening Sunset & Aperitivo',
    cityId: 'c-rome',
    city: 'Rome',
    country: 'Italy',
    region: 'Europe',
    category: 'Aperitivo',
    categoryGroup: 'food',
    time: '06:30 PM',
    duration: '2.0 Hours',
    durationMinutes: 120,
    cost: 3900,
    costTier: 'budget',
    costLabel: '₹ Budget',
    popularity: 4.8,
    reviewsCount: '3.1k',
    imageUrl: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=800&q=80',
    description: 'Bernini fountains, lively street artists, and refreshing Aperol Spritz cocktails.',
    highlights: ['Fountain of Four Rivers view', 'Gourmet bruschetta platters', 'Spritz cocktail tasting'],
  },
];

// 2. SYNCHRONIZED SECTIONS (Screen 5 Builder)
export const MASTER_SECTIONS: SectionItem[] = [
  {
    id: 'sec-1',
    sectionNumber: 1,
    title: 'Flight & Arrival in Paris',
    category: 'travel',
    city: 'Paris',
    country: 'France',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    description:
      'All the necessary information about this section. This can be anything like travel section, hotel or any other activity including international flights, airport shuttle, and private check-in.',
    startDate: 'Sep 10, 2026',
    endDate: 'Sep 13, 2026',
    budget: 35000,
    activities: MASTER_ACTIVITIES.slice(0, 3),
  },
  {
    id: 'sec-2',
    sectionNumber: 2,
    title: 'Swiss Alps Hotel Stay & Alpine Glacier Tour',
    category: 'hotel',
    city: 'Interlaken',
    country: 'Switzerland',
    imageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80',
    description:
      'All the necessary information about this section. This can be anything like travel section, hotel or any other activity including 4-star mountain lodge booking, panoramic train transfers, and ski equipment rental.',
    startDate: 'Sep 14, 2026',
    endDate: 'Sep 18, 2026',
    budget: 52000,
    activities: MASTER_ACTIVITIES.slice(6, 9),
  },
  {
    id: 'sec-3',
    sectionNumber: 3,
    title: 'Rome Historic City Center & Vatican Exploration',
    category: 'activity',
    city: 'Rome',
    country: 'Italy',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    description:
      'All the necessary information about this section. This can be anything like travel section, hotel or any other activity including Colosseum skip-the-line passes, Vatican City VIP tour, and local culinary tastings.',
    startDate: 'Sep 19, 2026',
    endDate: 'Sep 23, 2026',
    budget: 28000,
    activities: MASTER_ACTIVITIES.slice(12, 15),
  },
];

// 3. SYNCHRONIZED CALENDAR SPANS (Screen 10 / 11)
export const MASTER_CALENDAR_SPANS: TripSpanItem[] = [
  {
    id: 'ts-1',
    title: 'PARIS TRIP',
    city: 'Paris',
    country: 'France',
    color: '#2563EB',
    badgeBg: 'bg-blue-600 text-white',
    badgeText: 'text-blue-700 bg-blue-50 border-blue-200',
    startDay: 10,
    endDay: 13,
  },
  {
    id: 'ts-2',
    title: 'SWISS ALPS TOUR',
    city: 'Interlaken',
    country: 'Switzerland',
    color: '#7C3AED',
    badgeBg: 'bg-purple-600 text-white',
    badgeText: 'text-purple-700 bg-purple-50 border-purple-200',
    startDay: 14,
    endDay: 18,
  },
  {
    id: 'ts-3',
    title: 'ROME GETAWAY',
    city: 'Rome',
    country: 'Italy',
    color: '#059669',
    badgeBg: 'bg-emerald-600 text-white',
    badgeText: 'text-emerald-700 bg-emerald-50 border-emerald-200',
    startDay: 19,
    endDay: 23,
  },
];

// 4. SYNCHRONIZED DAY-WISE SCHEDULE MAP
export const MASTER_DAY_SCHEDULE: Record<number, DayPlan> = {
  10: {
    dayNumber: 1,
    date: 'Sep 10, 2026',
    dayOfMonth: 10,
    city: 'Paris',
    country: 'France',
    title: 'Arrival & River Seine Welcome',
    dailyCap: 12000,
    activities: MASTER_ACTIVITIES.slice(0, 3),
  },
  11: {
    dayNumber: 2,
    date: 'Sep 11, 2026',
    dayOfMonth: 11,
    city: 'Paris',
    country: 'France',
    title: 'Montmartre & Eiffel Tower Summit',
    dailyCap: 12000,
    activities: MASTER_ACTIVITIES.slice(3, 6),
  },
  14: {
    dayNumber: 5,
    date: 'Sep 14, 2026',
    dayOfMonth: 14,
    city: 'Interlaken',
    country: 'Switzerland',
    title: 'Glacier Express & Lake Brienz Cruise',
    dailyCap: 14000,
    activities: MASTER_ACTIVITIES.slice(6, 9),
  },
  15: {
    dayNumber: 6,
    date: 'Sep 15, 2026',
    dayOfMonth: 15,
    city: 'Interlaken',
    country: 'Switzerland',
    title: 'Jungfraujoch Summit & Cliff Thrills',
    dailyCap: 14000,
    activities: MASTER_ACTIVITIES.slice(9, 12),
  },
  19: {
    dayNumber: 10,
    date: 'Sep 19, 2026',
    dayOfMonth: 19,
    city: 'Rome',
    country: 'Italy',
    title: 'Colosseum Gladiator Arena & Pasta Walk',
    dailyCap: 12000,
    activities: MASTER_ACTIVITIES.slice(12, 15),
  },
  20: {
    dayNumber: 11,
    date: 'Sep 20, 2026',
    dayOfMonth: 20,
    city: 'Rome',
    country: 'Italy',
    title: 'Vatican Sistine Chapel & Angel Castle',
    dailyCap: 12000,
    activities: MASTER_ACTIVITIES.slice(15, 18),
  },
};
